POST localhost:8080/api/v1/jobs/add-job
Content-Type: application/json

{
  "jobId": 1,
  "jobTitle": "developer",
  "jobDescription" : "back end",
  "jobLocation": "chilonzor",
  "companyName": "Anor bank",
  "requiredSkills": ["Java", "Spring boot"],
  "jobType": "FULL_TIME",
  "workModel": "ONSITE"
}
###Get all Jobs
GET localhost:8080/api/v1/jobs

###Post apply To Job
POST localhost:8080/api/v1/jobs/apply
Content-Type: application/json

{
  "firstName": "Alisher",
  "lastName": "Aliyev",
  "userEmail": "alish7481@gmail.com",
  "phoneNumber": "998992565566",
  "primarySkills": ["spring boot, hibernate, postgresql"],
  "jobId": 1
}

###Get all Users
GET localhost:8080/api/v1/jobs/usersList

###Delete job By Id
DELETE localhost:8080/api/v1/jobs/delete/1

###Delete user By Phone Number
DELETE localhost:8080/api/v1/jobs/deleteByPhoneNumber/998945633300




